# Generated by Django 5.2.6 on 2025-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
